image:
  repository: zeus/postgres
  tag: "pg15-zhparser"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  nodePort: null

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""

resources: {}

postgres:
  database: zeus
  user: zeus
  password: zeus
  extensions:
    - vector
    - pg_trgm
    - zhparser
