image:
  repository: pgvector/pgvector
  tag: "pg15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""

resources: {}

postgres:
  database: zeus
  user: zeus
  password: zeus
  extensions:
    - vector
