image:
  repository: zeus/postgres
  tag: "pg15-zhparser"
  pullPolicy: IfNotPresent
  # Optional: if you pull from a private registry, set this to a list of secret names.
  # Example: ["harbor-regcred"]
  pullSecrets: []

service:
  type: ClusterIP
  port: 5432
  nodePort: null

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ""

resources: {}

postgres:
  database: zeus
  user: zeus
  password: zeus
  extensions:
    - vector
    - pg_trgm
    - zhparser
