apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.fullname" . }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "langfuse.databaseUrl" . | b64enc | quote }}
  nextauth-secret: {{ .Values.auth.nextAuthSecret | b64enc | quote }}
  salt: {{ .Values.auth.salt | b64enc | quote }}
