postgres:
  service:
    type: NodePort
    nodePort: 30432

rustfs:
  service:
    type: NodePort
    nodePort: 30900
    consoleNodePort: 30901

backend:
  enabled: false

frontend:
  enabled: false
