apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banana-slides.fullname" . }}
  labels:
    {{- include "banana-slides.labels" . | nindent 4 }}
type: Opaque
data:
  nano-banana-api-key: {{ .Values.nanoBanana.apiKey | b64enc | quote }}
  {{- if and .Values.redis.enabled .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
